### ISSUE TITLE
Install Issues and beyond

### ISSUE THREAD

**Issue by erock67** [ignacionelson/ProjectSend#268]
Forgive me if this has been addressed. 
I would like to determine whether I have a permissions error or PHP error. 

I have installed the package r756 and immediately got the error on the screen saying: "Please try again.
exception 'PDOException' " (see below  Error 1) 

I have checked the php.ini and it shows: 

PDO
PDO support	enabled
PDO drivers	mysql, sqlite, sqlite2

pdo_mysql
PDO Driver for MySQL	enabled
Client API version	5.5.41
Directive	Local Value	Master Value
pdo_mysql.default_socket	/tmp/mysql.sock	/tmp/mysql.sock

pdo_sqlite
PDO Driver for SQLite 3.x	enabled
SQLite Library	3.7.7.1

So, I saw that the database.php file was updated recently and replaced it with the fresh code. 
By doing so, I received a "PDO" error but it enabled the install to complete. (see error 2)

However, when I access the admin panel, I am not able to access manage-files.php. After uploading images, and selecting "Use file's absolute path". 
Second,  I am not able to view the thumbnail of the images as a user in 'view my files'. 

I wonder if there is a list of file permissions is should be set to?

Any insight on how to get this working 100% would be greatly appreciated. 

Eirik 

ERROR 1 
**First Error Received. Install did not complete:** 
`There seems to be an error. Please try again.
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:31 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(31): PDOStatement->execute(Array) #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table '6924_media_sitename.tbl_files_relations' (errno: 150)' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:31 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(31): PDOStatement->execute(Array) #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table '6924_media_sitename.tbl_notifications' (errno: 150)' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:31 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(31): PDOStatement->execute(Array) #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table '6924_media_sitename.tbl_downloads' doesn't exist' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:24 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(24): PDO->prepare('CREATE TABLE IF...') #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table '6924_media_sitename.tbl_categories_relations' (errno: 150)' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:31 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(31): PDOStatement->execute(Array) #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}`

Error 2  
**Second Error Received: Install Completed...However**
`There seems to be an error. Please try again.
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table '6924_media_sitename.tbl_downloads' doesn't exist' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:24 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(24): PDO->prepare('CREATE TABLE IF...') #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php:31 Stack trace: #0 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(31): PDOStatement->execute(Array) #1 /usr/www/virtual/domain/media.sitename.com/ProjectSend-r756/install/index.php(108): try_query(Array) #2 {main}`

**Comment by erock67** [comment]
Well, the good news is, I discovered the issue and was able to do a clean install. 
tbl_downloads was somehow hidden (possibly from previous attempts) on my database. I wasn't able to find it on a search, or write over it either. 
So I deleted the entire db and started over. 

During the install, the system did not create a config file,  so I copied the sample config file and entered the info through the backend.  
Once done, it installed like a charm through the web GUI. 

I'm still plagued with thumbnails not showing. I know there's another issue open and I'll refer to that.
