### ISSUE TITLE
New Install ... error sql 

### ISSUE THREAD

**Issue by andrelec1** [ignacionelson/ProjectSend#365]
Hello , i try to install the project on my server and i get this error : 

`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiry_date' in /www/clients/files/install/index.php:31 Stack trace: #0 /www/clients/files/install/index.php(31): PDOStatement->execute(Array) #1 /www/clients/files/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /www/clients/files/install/index.php:31 Stack trace: #0 /www/clients/files/install/index.php(31): PDOStatement->execute(Array) #1 /www/clients/files/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /www/clients/files/install/index.php:31 Stack trace: #0 /www/clients/files/install/index.php(31): PDOStatement->execute(Array) #1 /www/clients/files/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /www/clients/files/install/index.php:31 Stack trace: #0 /www/clients/files/install/index.php(31): PDOStatement->execute(Array) #1 /www/clients/files/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /www/clients/files/install/index.php:31 Stack trace: #0 /www/clients/files/install/index.php(31): PDOStatement->execute(Array) #1 /www/clients/files/install/index.php(108): try_query(Array) #2 {main}`

**Comment by andrelec1** [comment]
change in /install/database.php
line 26:
'expiry_date' TIMESTAMP NOT NULL DEFAULT '2038-01-18 22:00:00'

0000-00-00-00:00:00 is not in range of timestamp -_-"
