### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Duzga** [ignacionelson/ProjectSend#429]
After click install  button:
`There seems to be an error. Please try again.
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiry_date' in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php:31 Stack trace: #0 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(31): PDOStatement->execute(Array) #1 /usr/local/www/ns1.kemcity.net/data/projectsend/install/index.php(108): try_query(Array) #2 {main}`

**Comment by thehouseofho** [comment]
You should be able to resolve this issue by editing the 'expiry_date' value located in /install/database.php to TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
